<a href="https://colab.research.google.com/github/Nargis45/feature_engineering/blob/main/Handling_imbalanced_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install imbalanced-learn  

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# display all the columns of the dataframe
pd.pandas.set_option('display.max_columns',None)

In [ ]:
#mounting the drive to import the file
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [89]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/creditcard.csv')

In [90]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Amount  Class  
0  149.62      0  
1    2.69      0  
2  378.66      0  
3  123.50      0  
4   69.99      0

In [91]:
df.shape

(284807, 31)

In [92]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [93]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [94]:
# ind. and dep. variables
X=df.drop('Class', axis=1)
y=df.Class

In [95]:
#cross validation like KFold and hyperparameter tuning

In [96]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

In [97]:
log_class=LogisticRegression()
grid={'C':10.0**np.arange(-2,3), 'penalty':['l1', 'l2']}
cv=KFold(n_splits=5, shuffle=False, random_state=None)

In [98]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, train_size=0.7)

In [99]:
clf=GridSearchCV(log_class, grid, cv=cv, n_jobs=-1, scoring='f1_macro')
clf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py:703: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-pack

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [100]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85240    36]
 [   61   106]]
0.9988647402361809
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85276
           1       0.75      0.63      0.69       167

    accuracy                           1.00     85443
   macro avg       0.87      0.82      0.84     85443
weighted avg       1.00      1.00      1.00     85443



In [101]:
y_train.value_counts()

0    199039
1       325
Name: Class, dtype: int64

In [102]:
class_weight=dict({0:1,1:100}) # giving '1' 100 times more importance than '0'

In [103]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train, y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [104]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85270     6]
 [   41   126]]
0.9994499256814484
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85276
           1       0.95      0.75      0.84       167

    accuracy                           1.00     85443
   macro avg       0.98      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



# **under sampling**

In [105]:
# using under sampling reduce the points of the maximum labels but it should not be used for big dataset as data can be lost.

In [106]:
y_train.value_counts()

0    199039
1       325
Name: Class, dtype: int64

In [107]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8)
X_train_ns,y_train_ns=ns.fit_resample(X_train, y_train)
print('The number of classes before fit {}'.format(Counter(y_train)))
print('The number of classes after fit {}'.format(Counter(y_train_ns)))

/usr/local/lib/python3.7/dist-packages/imblearn/utils/_validation.py:590: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning,


The number of classes before fit Counter({0: 199039, 1: 325})
The number of classes after fit Counter({0: 406, 1: 325})


In [108]:
0.8*426 #80% of 426

340.8

In [109]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train_ns, y_train_ns)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [110]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[84904   372]
 [   23   144]]
0.9953770349823859
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85276
           1       0.28      0.86      0.42       167

    accuracy                           1.00     85443
   macro avg       0.64      0.93      0.71     85443
weighted avg       1.00      1.00      1.00     85443



# **over sampling**

In [111]:
from imblearn.over_sampling import RandomOverSampler

In [112]:
os=RandomOverSampler(0.75)
X_train_os,y_train_os=os.fit_resample(X_train, y_train)
print('The number of classes before fit {}'.format(Counter(y_train)))
print('The number of classes after fit {}'.format(Counter(y_train_os)))

/usr/local/lib/python3.7/dist-packages/imblearn/utils/_validation.py:590: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning,


The number of classes before fit Counter({0: 199039, 1: 325})
The number of classes after fit Counter({0: 199039, 1: 149279})


In [113]:
0.5*199023

99511.5

In [114]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train_os, y_train_os)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [115]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85269     7]
 [   48   119]]
0.9993562960102056
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85276
           1       0.94      0.71      0.81       167

    accuracy                           1.00     85443
   macro avg       0.97      0.86      0.91     85443
weighted avg       1.00      1.00      1.00     85443



# **SMOTETomek**

uses combination of both overs ampling and under sampling

It creates new points

In [125]:
from imblearn.combine import SMOTETomek

In [126]:
os=SMOTETomek(0.75)
X_train_os,y_train_os=os.fit_resample(X_train, y_train)
print('The number of classes before fit {}'.format(Counter(y_train)))
print('The number of classes after fit {}'.format(Counter(y_train_os)))

/usr/local/lib/python3.7/dist-packages/imblearn/utils/_validation.py:590: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning,


The number of classes before fit Counter({0: 199039, 1: 325})
The number of classes after fit Counter({0: 198552, 1: 148792})


In [88]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_os, y_train_os)

KeyboardInterrupt: ignored

In [ ]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# **Ensemble Techniques**

In [122]:
from imblearn.ensemble import EasyEnsembleClassifier

In [123]:
easy=EasyEnsembleClassifier()
easy.fit(X_train, y_train)

EasyEnsembleClassifier()

In [124]:
y_pred=easy.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[82282  2994]
 [   18   149]]
0.9647484287770794
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     85276
           1       0.05      0.89      0.09       167

    accuracy                           0.96     85443
   macro avg       0.52      0.93      0.54     85443
weighted avg       1.00      0.96      0.98     85443

